### ISSUE TITLE
The control template should not deal with movement

### ISSUE THREAD

**Issue by torwag** [asger-weirsoee/sway-smart-workspaces#2]
I believe as movement of windows is something independent of sway-smart-workspaces, it should not be in the config template. I for once, got error messages as I had those movements defined within the sway config as well.
I will submit a PR for it... #3 
Don't worry I know you are busy and do not expect a quick reply,  good luck with your CS exams.

**Comment by asger-weirsoee** [comment]
This is fixed with #3 Thanks :)
