### ISSUE TITLE
Use full output names instead of the short names

### ISSUE THREAD

**Issue by torwag** [asger-weirsoee/sway-smart-workspaces#5]
Using two docking station, I noticed that the names of the output ports seems not always consistent and permanent. E.g. DP-1 becomes DP-4 on the next reconnect. 
That messes with the settings.
Would it be possible to use the full name, which sway usually also allows for its own output configs.
e.g. "Dell Inc. DELL U2414H 9TG463AP4L2L" instead of DP-4
That would be unique among different workplaces and the config would work more reliable.

**Comment by torwag** [comment]
Inspecting the code, I think it should be possible relatively easy, however the naming scheme for the config files would be a bit odd. 
Is there a reason you prefer multiple files over a single config file?
I also do not get the meaning of the first line of a config file which starts with 
`output <name>` e.g. `output DP-4`

I believe the change need to be done here:
https://github.com/asger-weirsoee/sway-smart-workspaces/blob/8818e519b6024b306344e81d00fc0937aa651819/sway_smart_workspace/smart_workspace.py#L75
instead of `output.name` one could use 
`f'{output.make} {output.model} {output.serial}'`
But again, the naming scheme of the config files would be a little odd and error prone.

**Comment by asger-weirsoee** [comment]
Good catch!
I've not had this problem before, but I can see why it might be an issue.

So, I think your suggestion might be the best option, as I don't really know if there is any way to ensure uniqueness in other ways, unless doing some hashing of the model and serial number. 🤔

Anyways, this will be added to my Todo list!

**Comment by torwag** [comment]
Hi thanks for looking into it.
I would say the best way would be to use the same output naming scheme as the output command of sway itself. This would result in less confusion among users as the generated config files look exactly like one would expect them from a sway config.
Sway creates the name by combining` f'{output.make} {output.model} {output.serial}'` including the spaces. 
My only concern would be that the output name is also the file-name and this looks odd, at least on a file name level.
BTW. I also do not get what the very first command in the sway configs do e.g. `output DP-4`. Maybe I overlooked it, but I can't find a function for just calling the output command and the output-name.
Another question would be, why using so many config files instead of a single large one?

**Comment by torwag** [comment]
How does the PR implement the full output name?
I can see that there were some changes to this by adding a flag `full` but I can't see how to set it.
